# spring:
#   application:
#     name: order
#   datasource:
#     driver-class-name: com.mysql.jdbc.Driver
#     url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
#     username: root
#     password: 123456
#   jpa:
#     show-sql: true
# eureka:
#   client:
#     service-url:
#       defaultZone: http://127.0.0.1:8761/eureka/
# server:
#   port: 8673
spring:
  rabbitmq:
      host: 192.168.76.137
      port: 5672
      username: guest
      password: guest
